{% set name = "samplex" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/samplex-{{ version }}.tar.gz
  sha256: 903112a33dbcab71d3f1c37a3cb81a4dd023aa126f35e43ca78a9660e2e7281c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - tqdm
    - mlx

test:
  imports:
    - samplex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tedwards2412/samplex
  summary: Samplers in MLX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
